#!/bin/sh

"$TESTDIR/hghave" caseguard || exit 80

echo '% override test'
hg init repo3
cat << EOF >> $HGRCPATH
[extensions]
caseguard = 
EOF
cd repo3

# simple case collision
echo com1 > com1
hg add -w com1 || echo '% disable windows check failure'
echo bar > bar
hg add bar
mv bar BAR
hg add -o BAR || echo '% disable collision check failure'
mv BAR Bar
echo aux > aux
hg add -w
hg add -o

hg st

cd ..
rm -rf repo3