#!/bin/sh

"$TESTDIR/hghave" caseguard || exit 80
"$TESTDIR/hghave" no-icasefs || exit 80

echo '% case-sensitive filesystem test'
hg init repo2
cat << EOF >> $HGRCPATH
[extensions]
caseguard = 
EOF
cd repo2

# multiple files, diff case
echo foo > foo
echo FOO > FOO
echo Foo > Foo
echo fOO > fOO
hg add && echo '% collision in initial add'

hg st

hg add foo FOO && echo '% collision in argument list'

echo '% case-sensitive override test'
echo baz > baz
hg add baz
mv baz BAZ
hg add -o BAZ || echo '% disable collision check failure'
mv BAZ Baz
hg add -o

hg st

cd ..
rm -rf repo2