#!/bin/sh

"$TESTDIR/hghave" caseguard || exit 80
"$TESTDIR/hghave" icasefs || exit 80

echo '% case-insensitive filesystem test'
hg init repo1
cat << EOF >> $HGRCPATH
[extensions]
caseguard = 
EOF
cd repo1

# simple case collision
echo foo > foo
hg add foo
hg st
mv foo FOO
hg add FOO && echo '% collision with pending addition'
mv FOO foo
hg ci -m addfoo
mv foo FOO
hg add FOO && echo '% collision with tracked file'
mv FOO foo
echo FO > FO
hg add FO || echo '% false positive, partial filename match'

hg st

echo '% case-insensitive override test'
echo baz > baz
hg add baz
mv baz BAZ
hg add -o BAZ || echo '% disable collision check failure'
mv BAZ Baz
hg add -o

hg st

cd ..
rm -rf repo1